import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // HERE WE SET THE STALE TIME FOR DYNAMIC DATA TO 30 SECONDS
  // THIS MEANS THAT NEXT.JS WILL CACHE THE DYNAMIC DATA FOR 30 SECONDS
  // AND SERVE THE CACHED DATA FOR SUBSEQUENT REQUESTS WITHIN THAT TIME FRAME
  // AFTER 30 SECONDS, NEXT.JS WILL REVALIDATE THE DATA ON THE NEXT REQUEST
  // THIS IS USEFUL FOR ECOMMERCE SITES WHERE PRODUCT DATA MAY CHANGE FREQUENTLY
  // BUT WE WANT TO BALANCE FRESHNESS WITH PERFORMANCE
  experimental: {
    staleTimes: {
      dynamic: 30,
    },
  },
};

export default nextConfig;
