import { WIX_SESSION_COOKIE } from "@/constants";
import { Tokens } from "@wix/sdk";
import Cookies from "js-cookie";
import { myWixClient } from "./wix-client.base";

// FUNCTION TO CREATE WIX CLIENT ON THE BROWSER WITH TOKENS FROM JS COOKIE
// THINK OF THE WIX CLIENT AS A WALKIE TALKIE THAT TALKS TO WIX SERVERS.
// THE WALKIE TALKIE NEEDS AN ID BADGE (TOKENS) SO WIX KNOWS WHO IS TALKING.

// THIS FILE RUNS IN THE BROWSER.
// THE BROWSER BELONGS TO ONE USER.
// THAT USER HAS THEIR OWN COOKIES AND THEIR OWN MEMORY SPACE.

// WE READ THE TOKENS FROM THE BROWSER COOKIE.
// THESE TOKENS IDENTIFY THE CURRENT VISITOR TO WIX.
const tokens: Tokens = JSON.parse(Cookies.get(WIX_SESSION_COOKIE) || "{}");

// WE CREATE ONE WIX CLIENT INSTANCE FOR THE BROWSER.
//
// WHY THIS IS SAFE:
//
// - EACH USER HAS THEIR OWN BROWSER
// - EACH BROWSER HAS ITS OWN MEMORY
// - TOKENS ARE ALREADY USER SPECIFIC
//
// ANALOGY:
// THIS IS LIKE GIVING A USER A KEY FOB WHEN THEY ENTER A BUILDING.
// THEY USE THE SAME KEY FOB TO OPEN ALL DOORS.
// YOU DO NOT ISSUE A NEW KEY FOB EVERY TIME THEY OPEN A DOOR.

// REUSING THE SAME CLIENT IS GOOD FOR PERFORMANCE.
// NO NEED TO RECREATE IT ON EVERY CLICK.
// NO NEED FOR REACT CONTEXT OR PROVIDERS.
// THE CLIENT ALREADY KNOWS WHO THE USER IS.
export const wixBrowserClient = myWixClient(tokens);

// IMPORTANT DIFFERENCE BETWEEN BROWSER AND SERVER:
//
// SERVER:
// - ONE SERVER HANDLES MANY USERS AT THE SAME TIME
// - MEMORY IS SHARED BETWEEN REQUESTS
// - YOU MUST CREATE A NEW CLIENT PER REQUEST
// - TOKENS MUST BE READ FROM COOKIES EACH TIME
//
// BROWSER:
// - ONE USER PER ENVIRONMENT
// - MEMORY IS ISOLATED
// - SAFE TO REUSE A SINGLE CLIENT INSTANCE
// - TOKENS STAY THE SAME DURING THE SESSION
//
// SIMPLE RULE:
// BROWSER = REUSE CLIENT
// SERVER = NEW CLIENT PER REQUEST
